name: 'Drop Nexus Staging Repo'
description: 'Drops a staged repo, with a given ID, on https://oss.sonatype.org/.'
inputs:
  username: 
    description: 'Your Sonatype username, same the Sonatype Jira one.'
    required: true
  password: 
    description: 'Your Sonatype password, same the Sonatype Jira one.'
    required: true
  staging_repository_id: 
    description: 'The ID of the staged repository to drop.'
    required: true
  base_url: 
    description: 'The url of your nexus repository, defaults to OSSRH (https://oss.sonatype.org/service/local/)'
    default: 'https://oss.sonatype.org/service/local/'
runs:
  using: 'docker'
  image: 'Dockerfile'